<a href="https://colab.research.google.com/github/Rogerio-mack/AD_solucao/blob/main/Aula_02_Cars93_exploracao_inicial_solucao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/MASS/Cars93.csv")
df.drop(columns="rownames",inplace=True)
df.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,Front,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

# Exploração Inicial (Conhecendo os Dados)

In [ ]:
df.head() # df.tail()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,Front,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

In [ ]:
df[ df.Manufacturer == 'Volvo' ]

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
91,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,Rear,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,Front,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

In [ ]:
df.shape

(93, 27)

In [ ]:
len(df)

93

In [ ]:
df.dtypes

Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city                int64
MPG.highway             int64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower              int64
RPM                     int64
Rev.per.mile            int64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers              int64
Length                  int64
Wheelbase               int64
Width                   int64
Turn.circle             int64
Rear.seat.room        float64
Luggage.room          float64
Weight                  int64
Origin                 object
Make                   object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Manufacturer        93 non-null     object
 1   Model               93 non-null     object
 2   Type                93 non-null     object
 3   Min.Price           93 non-null     float64
 4   Price               93 non-null     float64
 5   Max.Price           93 non-null     float64
 6   MPG.city            93 non-null     int64
 7   MPG.highway         93 non-null     int64
 8   AirBags             59 non-null     object
 9   DriveTrain          93 non-null     object
 10  Cylinders           93 non-null     object
 11  EngineSize          93 non-null     float64
 12  Horsepower          93 non-null     int64
 13  RPM                 93 non-null     int64
 14  Rev.per.mile        93 non-null     int64
 15  Man.trans.avail     93 non-null     object
 16  Fuel.tank.capacity  93 non-null     float64
 17  Passengers          93 non-null     int64
 18  Length              93 non-null     int64
 19  Wheelbase           93 non-null     int64
 20  Width               93 non-null     int64
 21  Turn.circle         93 non-null     int64
 22  Rear.seat.room      91 non-null     float64
 23  Luggage.room        82 non-null     float64
 24  Weight              93 non-null     int64
 25  Origin              93 non-null     object
 26  Make                93 non-null     object
dtypes: float64(7), int64(11), object(9)
memory usage: 19.7+ KB

In [ ]:
df.columns

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

In [ ]:
df.describe()

,Min.Price,Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight
count,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000,93.000000
mean,17.125806,19.509677,21.898925,22.365591,29.086022,2.667742,143.827957,5280.645161,2332.204301,16.664516,5.086022,183.204301,103.946237,69.376344,38.956989,27.829670,13.890244,3072.903226
std,8.746029,9.659430,11.030457,5.619812,5.331726,1.037363,52.374410,596.731690,496.506525,3.279370,1.038979,14.602382,6.819674,3.778986,3.223265,2.989072,2.997967,589.896510
min,6.700000,7.400000,7.900000,15.000000,20.000000,1.000000,55.000000,3800.000000,1320.000000,9.200000,2.000000,141.000000,90.000000,60.000000,32.000000,19.000000,6.000000,1695.000000
25%,10.800000,12.200000,14.700000,18.000000,26.000000,1.800000,103.000000,4800.000000,1985.000000,14.500000,4.000000,174.000000,98.000000,67.000000,37.000000,26.000000,12.000000,2620.000000
50%,14.700000,17.700000,19.600000,21.000000,28.000000,2.400000,140.000000,5200.000000,2340.000000,16.400000,5.000000,183.000000,103.000000,69.000000,39.000000,27.500000,14.000000,3040.000000
75%,20.300000,23.300000,25.300000,25.000000,31.000000,3.300000,170.000000,5750.000000,2565.000000,18.800000,6.000000,192.000000,110.000000,72.000000,41.000000,30.000000,15.000000,3525.000000
max,45.400000,61.900000,80.000000,46.000000,50.000000,5.700000,300.000000,6500.000000,3755.000000,27.000000,8.000000,219.000000,119.000000,78.000000,45.000000,36.000000,22.000000,4105.000000

In [ ]:
df.describe(include="all")

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
count,93,93,93,93.000000,93.000000,93.000000,93.000000,93.000000,59,93,...,93.000000,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000,93.000000,93,93
unique,32,93,6,NaN,NaN,NaN,NaN,NaN,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,93
top,Chevrolet,Integra,Midsize,NaN,NaN,NaN,NaN,NaN,Driver only,Front,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USA,Acura Integra
freq,8,1,22,NaN,NaN,NaN,NaN,NaN,43,67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48,1
mean,NaN,NaN,NaN,17.125806,19.509677,21.898925,22.365591,29.086022,NaN,NaN,...,5.086022,183.204301,103.946237,69.376344,38.956989,27.829670,13.890244,3072.903226,NaN,NaN
std,NaN,NaN,NaN,8.746029,9.659430,11.030457,5.619812,5.331726,NaN,NaN,...,1.038979,14.602382,6.819674,3.778986,3.223265,2.989072,2.997967,589.896510,NaN,NaN
min,NaN,NaN,NaN,6.700000,7.400000,7.900000,15.000000,20.000000,NaN,NaN,...,2.000000,141.000000,90.000000,60.000000,32.000000,19.000000,6.000000,1695.000000,NaN,NaN
25%,NaN,NaN,NaN,10.800000,12.200000,14.700000,18.000000,26.000000,NaN,NaN,...,4.000000,174.000000,98.000000,67.000000,37.000000,26.000000,12.000000,2620.000000,NaN,NaN
50%,NaN,NaN,NaN,14.700000,17.700000,19.600000,21.000000,28.000000,NaN,NaN,...,5.000000,183.000000,103.000000,69.000000,39.000000,27.500000,14.000000,3040.000000,NaN,NaN
75%,NaN,NaN,NaN,20.300000,23.300000,25.300000,25.000000,31.000000,NaN,NaN,...,6.000000,192.000000,110.000000,72.000000,41.000000,30.000000,15.000000,3525.000000,NaN,NaN
max,NaN,NaN,NaN,45.400000,61.900000,80.000000,46.000000,50.000000,NaN,NaN,...,8.000000,219.000000,119.000000,78.000000,45.000000,36.000000,22.000000,4105.000000,NaN,NaN

# Seleção básica de dados

In [ ]:
df.Manufacturer

0          Acura
1          Acura
2           Audi
3           Audi
4            BMW
         ...
88    Volkswagen
89    Volkswagen
90    Volkswagen
91         Volvo
92         Volvo
Name: Manufacturer, Length: 93, dtype: object

In [ ]:
df.Manufacturer.value_counts()

Manufacturer
Chevrolet        8
Ford             8
Dodge            6
Mazda            5
Pontiac          5
Oldsmobile       4
Hyundai          4
Buick            4
Nissan           4
Toyota           4
Volkswagen       4
Subaru           3
Honda            3
Geo              2
Audi             2
Acura            2
Volvo            2
Mitsubishi       2
Mercedes-Benz    2
Lexus            2
Chrysler         2
Cadillac         2
Eagle            2
Lincoln          2
Mercury          2
Infiniti         1
BMW              1
Chrylser         1
Plymouth         1
Saab             1
Saturn           1
Suzuki           1
Name: count, dtype: int64

In [ ]:
df.Price

0     15.9
1     33.9
2     29.1
3     37.7
4     30.0
      ...
88    19.7
89    20.0
90    23.3
91    22.7
92    26.7
Name: Price, Length: 93, dtype: float64

In [ ]:
df.Price.mean()

np.float64(19.50967741935484)

In [ ]:
df[ df.Manufacturer == 'Chevrolet' ]

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
11,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25,36,NaN,Front,...,5,182,101,66,38,25.0,13.0,2490,USA,Chevrolet Cavalier
12,Chevrolet,Corsica,Compact,11.4,11.4,11.4,25,34,Driver only,Front,...,5,184,103,68,39,26.0,14.0,2785,USA,Chevrolet Corsica
13,Chevrolet,Camaro,Sporty,13.4,15.1,16.8,19,28,Driver & Passenger,Rear,...,4,193,101,74,43,25.0,13.0,3240,USA,Chevrolet Camaro
14,Chevrolet,Lumina,Midsize,13.4,15.9,18.4,21,29,NaN,Front,...,6,198,108,71,40,28.5,16.0,3195,USA,Chevrolet Lumina
15,Chevrolet,Lumina_APV,Van,14.7,16.3,18.0,18,23,NaN,Front,...,7,178,110,74,44,30.5,NaN,3715,USA,Chevrolet Lumina_APV
16,Chevrolet,Astro,Van,14.7,16.6,18.6,15,20,NaN,4WD,...,8,194,111,78,42,33.5,NaN,4025,USA,Chevrolet Astro
17,Chevrolet,Caprice,Large,18.0,18.8,19.6,17,26,Driver only,Rear,...,6,214,116,77,42,29.5,20.0,3910,USA,Chevrolet Caprice
18,Chevrolet,Corvette,Sporty,34.6,38.0,41.5,17,25,Driver only,Rear,...,2,179,96,74,43,NaN,NaN,3380,USA,Chevrolet Corvette

# Qual o preço médio dos veículos Chevrolet?

In [ ]:
Chevrolet = df[ df.Manufacturer == 'Chevrolet' ]

In [ ]:
Chevrolet.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
11,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25,36,NaN,Front,...,5,182,101,66,38,25.0,13.0,2490,USA,Chevrolet Cavalier
12,Chevrolet,Corsica,Compact,11.4,11.4,11.4,25,34,Driver only,Front,...,5,184,103,68,39,26.0,14.0,2785,USA,Chevrolet Corsica
13,Chevrolet,Camaro,Sporty,13.4,15.1,16.8,19,28,Driver & Passenger,Rear,...,4,193,101,74,43,25.0,13.0,3240,USA,Chevrolet Camaro
14,Chevrolet,Lumina,Midsize,13.4,15.9,18.4,21,29,NaN,Front,...,6,198,108,71,40,28.5,16.0,3195,USA,Chevrolet Lumina
15,Chevrolet,Lumina_APV,Van,14.7,16.3,18.0,18,23,NaN,Front,...,7,178,110,74,44,30.5,NaN,3715,USA,Chevrolet Lumina_APV

In [ ]:
Chevrolet.describe()

,Min.Price,Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight
count,8.000000,8.000000,8.000000,8.00000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.00000,8.00000,7.000000,5.000000,8.000000
mean,16.087500,18.187500,20.325000,19.62500,27.625000,3.600000,161.875000,4775.000000,1965.625000,19.100000,5.375000,190.250000,105.750000,72.75000,41.37500,28.285714,15.200000,3342.500000
std,7.966078,8.304463,8.921683,3.73927,5.370222,1.353303,62.446406,471.320334,511.918224,4.249706,1.846812,12.127301,6.584614,4.16619,2.13391,3.173551,2.949576,534.235101
min,8.500000,11.400000,11.400000,15.00000,20.000000,2.200000,110.000000,4000.000000,1350.000000,15.200000,2.000000,178.000000,96.000000,66.00000,38.00000,25.000000,13.000000,2490.000000
25%,12.900000,14.675000,17.700000,17.00000,24.500000,2.200000,110.000000,4500.000000,1630.000000,15.575000,4.750000,181.250000,101.000000,70.25000,39.75000,25.500000,13.000000,3092.500000
50%,14.050000,16.100000,18.350000,18.50000,27.000000,3.600000,162.500000,4900.000000,1797.500000,18.250000,5.500000,188.500000,105.500000,74.00000,42.00000,28.500000,14.000000,3310.000000
75%,15.525000,17.150000,18.850000,22.00000,30.250000,4.475000,170.000000,5200.000000,2433.750000,20.750000,6.250000,195.000000,110.250000,74.75000,43.00000,30.000000,16.000000,3763.750000
max,34.600000,38.000000,41.500000,25.00000,36.000000,5.700000,300.000000,5200.000000,2665.000000,27.000000,8.000000,214.000000,116.000000,78.00000,44.00000,33.500000,20.000000,4025.000000

In [ ]:
Chevrolet.Price.mean()

np.float64(18.1875)

In [ ]:
df[ df.Manufacturer == 'Chevrolet' ].Price.mean()

np.float64(18.1875)

In [ ]:
#
# prompt: Dê o price médio dos veículos Chevrolet de df
df[ df.Manufacturer == 'Chevrolet' ].Price.mean()

np.float64(18.1875)

# Exercício

1. Faça uma exploração inicial dos dados de `penguins` em https://github.com/INRIA/scikit-learn-mooc/tree/main/datasets

2. Obtenha o nome das espécies de penguins

3. Obtenha o peso médio de cada espécie

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/INRIA/scikit-learn-mooc/main/datasets/penguins.csv")
df.head()

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007-11-11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,2007-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN

In [ ]:
df.Species.value_counts()

Species
Adelie Penguin (Pygoscelis adeliae)          152
Gentoo penguin (Pygoscelis papua)            124
Chinstrap penguin (Pygoscelis antarctica)     68
Name: count, dtype: int64

### Notas

- `.unique()` e iterações
- `df.field_A` = `df["field_A"]` = `cpo ="field_A"` + `df[cpo]`
- Solução alternativa com `groupby()`

In [ ]:
for specie in df.Species.unique():
    print(f'{specie},: {df[ df.Species == specie ]["Body Mass (g)"].mean():.2f}')

Adelie Penguin (Pygoscelis adeliae),: 3700.66
Gentoo penguin (Pygoscelis papua),: 5076.02
Chinstrap penguin (Pygoscelis antarctica),: 3733.09

In [ ]:
df.groupby("Species")["Body Mass (g)"].mean()

Species
Adelie Penguin (Pygoscelis adeliae)          3700.662252
Chinstrap penguin (Pygoscelis antarctica)    3733.088235
Gentoo penguin (Pygoscelis papua)            5076.016260
Name: Body Mass (g), dtype: float64